<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Alumni extends Seeder
{
	public function run()
	{
		$faker = \Faker\Factory::create('id_ID');

		$data = [
			[
				"nama" => "Dummy_dummy",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Sungai Penuh",
				"tanggal_lahir" => "1997-01-25",
				"telp_alumni" => "081299594151",
				"alamat_alumni" => "Jr. Abdul Rahmat No. 755, Tangerang 47637, SulUt",
				"kota" => "Kabupaten Tuban",
				"provinsi" => "Jawa Timur",
				"negara" => "Indonesia",
				"status_bekerja" => "0",
				"perkiraan_pensiun" => "1978",
				"jabatan_terakhir" => "amet",
				"aktif_pns" => "0",
				"deskripsi" => "Maiores ut quasi beatae vel quisquam. Quo aut iusto et nobis et blanditiis non. Animi in architecto et iusto occaecati mollitia vel.",
				"ig" => "dummy_igza__",
				"fb" => "",
				"twitter" => "Dummy__",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "198109262004122002",
				"nip_bps" => "301820912",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Kartika Lismawati",
				"jenis_kelamin" => "Pr",
				"tempat_lahir" => "Palembang",
				"tanggal_lahir" => "1964-11-19",
				"telp_alumni" => "",
				"alamat_alumni" => "Jl. Lumbu Barat II B No. 82 Bl",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2022",
				"jabatan_terakhir" => "Kepala Subbidang Program dan Evaluasi Pendidikan dan Pelatihan Teknis dan Fungsional",
				"aktif_pns" => "1",
				"deskripsi" => "Test test 1 2 3",
				"ig" => "kartika123",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "196411191987022003",
				"nip_bps" => "340011691",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Budi Cahyono",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Bojonegoro",
				"tanggal_lahir" => "1964-06-08",
				"telp_alumni" => "",
				"alamat_alumni" => "Kp. Jati Griya Jatimas Asri",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2022",
				"jabatan_terakhir" => "Kepala BPS Kabupaten/Kota",
				"aktif_pns" => "1",
				"deskripsi" => "Hi there",
				"ig" => "boecah123",
				"fb" => "",
				"twitter" => "Budi Cahyono",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "196406081987021002",
				"nip_bps" => "340011692",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "1",
				"calamat" => "1",
				"cpendidikan" => "1",
				"cprestasi" => "0",
			],
			[
				"nama" => "Indra Susilo",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Jakarta Pusat",
				"tanggal_lahir" => "1964-06-07",
				"telp_alumni" => "081318869089",
				"alamat_alumni" => "Jl. Wibisana No. 6",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2022",
				"jabatan_terakhir" => "Kepala BPS Kabupaten/Kota",
				"aktif_pns" => "1",
				"deskripsi" => "Test123",
				"ig" => "indrass98",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "196406071987021001",
				"nip_bps" => "340011693",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "1",
				"calamat" => "1",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Erisman",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Jakarta Timur",
				"tanggal_lahir" => "1964-11-02",
				"telp_alumni" => "08129491174",
				"alamat_alumni" => "JL.SMART HOUSE KAV.B56",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2020",
				"jabatan_terakhir" => "Kepala BPS Kabupaten/Kota",
				"aktif_pns" => "0",
				"deskripsi" => "Saya adalah Kepala BPS Kabupaten/Kota",
				"ig" => "erisman222",
				"fb" => "",
				"twitter" => "erisman123",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "196411021987021001",
				"nip_bps" => "340011694",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "1",
				"calamat" => "1",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Ono Margiono",
				"jenis_kelamin" => "LK",
				"tempat_lahir" => "Jakarta Timur",
				"tanggal_lahir" => "1966-05-13",
				"telp_alumni" => "081214770887",
				"alamat_alumni" => "Jl. Pangeran Kejaksan Gg. Muja",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2024",
				"jabatan_terakhir" => "Kepala BPS Kabupaten/Kota",
				"aktif_pns" => "1",
				"deskripsi" => "good",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "196605131988021001",
				"nip_bps" => "340011828",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Sofan",
				"jenis_kelamin" => "LK",
				"tempat_lahir" => "Kebumen",
				"tanggal_lahir" => "1964-10-21",
				"telp_alumni" => "0811383762",
				"alamat_alumni" => "Jl Alamandar",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2022",
				"jabatan_terakhir" => "Kepala Bidang Statistik Produksi",
				"aktif_pns" => "1",
				"deskripsi" => "asyik",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "196410211988021001",
				"nip_bps" => "340011829",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Efliza",
				"jenis_kelamin" => "PR",
				"tempat_lahir" => "Medan",
				"tanggal_lahir" => "1965-04-28",
				"telp_alumni" => "0816228960",
				"alamat_alumni" => "Jl Masjid Nurul Falah No 14",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2025",
				"jabatan_terakhir" => "Kepala Direktorat Statistik Distribusi",
				"aktif_pns" => "1",
				"deskripsi" => "asyiap",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "196504281988022001",
				"nip_bps" => "340011855",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Oldestia Vianny",
				"jenis_kelamin" => "Pr",
				"tempat_lahir" => "Payakumbuh",
				"tanggal_lahir" => "1979-06-11",
				"telp_alumni" => "081274707292",
				"alamat_alumni" => "Jl Rantau 3 No. 3 Rt 003 Rw 01",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2037",
				"jabatan_terakhir" => "Statistisi Muda Seksi Analisis Statistik Lintas Sektor",
				"aktif_pns" => "1",
				"deskripsi" => "PNS",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "197906111999122001",
				"nip_bps" => "340015996",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Oemar Syarief Wibisono",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Jakarta",
				"tanggal_lahir" => "1994-09-29",
				"telp_alumni" => "082278449084",
				"alamat_alumni" => "Lorong Perdamaian Bedeng Akau",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2052",
				"jabatan_terakhir" => "Staf Seksi Integrasi Pengolahan dan Diseminasi Statistik",
				"aktif_pns" => "1",
				"deskripsi" => "gk tau",
				"ig" => "NULL",
				"fb" => "",
				"twitter" => "Omar",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "199409292017011001",
				"nip_bps" => "340057694",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Odry Syafwil",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Jakarta",
				"tanggal_lahir" => "1954-10-08",
				"telp_alumni" => "081574594320",
				"alamat_alumni" => "KOMPLEKS STATISTIK Jl. Statistik",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2019",
				"jabatan_terakhir" => "Lektor Kepala Tenaga Fungsional STIS",
				"aktif_pns" => "0",
				"deskripsi" => "Sudah pensiun",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "195410081979031004",
				"nip_bps" => "340006615",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Pradini Ajeng Gemellia",
				"jenis_kelamin" => "Pr",
				"tempat_lahir" => "Bandung",
				"tanggal_lahir" => "1989-10-13",
				"telp_alumni" => "08567485818",
				"alamat_alumni" => "Jl. Pelabuhan II Km 4,5 RT 2/8",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2047",
				"jabatan_terakhir" => "Staf Seksi Statistik Niaga dan Jasa",
				"aktif_pns" => "1",
				"deskripsi" => "hmm",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "198910132012112001",
				"nip_bps" => "340055881",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Lisiana Imana Yesani",
				"jenis_kelamin" => "PR",
				"tempat_lahir" => "Jakarta Pusat",
				"tanggal_lahir" => "1977-05-21",
				"telp_alumni" => "085283507222",
				"alamat_alumni" => "Jl. Kayu Manis VII No. 36",
				"kota" => "Jakarta Pusat",
				"provinsi" => "DKI Jakarta",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2035",
				"jabatan_terakhir" => "Kepala Seksi Statistik Sosial",
				"aktif_pns" => "1",
				"deskripsi" => "Asli jakarta hehe",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "197705211999012001",
				"nip_bps" => "340015738",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Sana Damarhita",
				"jenis_kelamin" => "PR",
				"tempat_lahir" => "Jakarta Selatan",
				"tanggal_lahir" => "1977-05-14",
				"telp_alumni" => "087722882289",
				"alamat_alumni" => "Perumahan Bumi Cinderaya Jl. C",
				"kota" => "Jakarta Selatan",
				"provinsi" => "DKI Jakarta",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2035",
				"jabatan_terakhir" => "Kepala Seksi Neraca Wilayah dan Analisis Statistik",
				"aktif_pns" => "1",
				"deskripsi" => "Haha hihi penempatan",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "197705141999011001",
				"nip_bps" => "340015739",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Krisdiana Galih",
				"jenis_kelamin" => "LK",
				"tempat_lahir" => "Bandung",
				"tanggal_lahir" => "1990-12-30",
				"telp_alumni" => "081261932301",
				"alamat_alumni" => "cluster hang lekir J9, batu IX",
				"kota" => "Bintan",
				"provinsi" => "Kepulauan Riau",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2049",
				"jabatan_terakhir" => "Kepala Subbagian Tata Usaha",
				"aktif_pns" => "1",
				"deskripsi" => "Sekarang rantau dulu bos",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "199012302014101001",
				"nip_bps" => "340056726",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "La Ode Ahmad Arafat",
				"jenis_kelamin" => "LK",
				"tempat_lahir" => "Ambon",
				"tanggal_lahir" => "1991-09-16",
				"telp_alumni" => "085733198934",
				"alamat_alumni" => "Jl. Raya Sambiroto, Dsn. Sambi",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2049",
				"jabatan_terakhir" => "Statistisi Pertama Seksi Diseminasi dan Layanan Statistik",
				"aktif_pns" => "1",
				"deskripsi" => "mantap ks teladan",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "340056728",
				"nip_bps" => "199109162014101002",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Aan Sujanah",
				"jenis_kelamin" => "Pr",
				"tempat_lahir" => "Jakarta Timur",
				"tanggal_lahir" => "1962-10-02",
				"telp_alumni" => "08116291011",
				"alamat_alumni" => "Maskoki Raya No 2",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"status_bekerja" => "0",
				"perkiraan_pensiun" => "2020",
				"jabatan_terakhir" => "Kepala Subbagian Penyimpanan",
				"aktif_pns" => "0",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "196210021986012001",
				"nip_bps" => "340011224",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Risma Pijayantini",
				"jenis_kelamin" => "Pr",
				"tempat_lahir" => "Palembang",
				"tanggal_lahir" => "1963-06-09",
				"telp_alumni" => "082183288585",
				"alamat_alumni" => "Perumnas Permata Biru Blok B3",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2021",
				"jabatan_terakhir" => "Kepala Bagian Tata Usaha",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "196306091986012001",
				"nip_bps" => "340011225",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Ade Rika Agus",
				"jenis_kelamin" => "Pr",
				"tempat_lahir" => "Bogor",
				"tanggal_lahir" => "1963-10-14",
				"telp_alumni" => "",
				"alamat_alumni" => "JL Bojong Kaler I/4 Cigadung",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"status_bekerja" => "0",
				"perkiraan_pensiun" => "",
				"jabatan_terakhir" => "Staf Seksi Neraca Produksi",
				"aktif_pns" => "0",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "196310141986012001",
				"nip_bps" => "340011226",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Haryoto Sutomo",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Jakarta Selatan",
				"tanggal_lahir" => "1962-07-02",
				"telp_alumni" => "",
				"alamat_alumni" => "Jl. Statistik II/32 Komplek St",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"status_bekerja" => "0",
				"perkiraan_pensiun" => "2011",
				"jabatan_terakhir" => "Staf Seksi Pengembangan Desain Sensus dan Survei Bidang Statistik Distribusi dan Jasa",
				"aktif_pns" => "0",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "",
				"nip_bps" => "",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "I Ketut Mertayasa",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Padangbae",
				"tanggal_lahir" => "1968-07-26",
				"telp_alumni" => "081271067114",
				"alamat_alumni" => "JL. BYPASS, KOBA, BANGKA TENGA",
				"kota" => "Bangka Tengah",
				"provinsi" => "Bangka Belitung",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2026",
				"jabatan_terakhir" => "Kepala BPS Kabupaten/Kota",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "196807261992111001",
				"nip_bps" => "340013357",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Ni Putu Beliana Puspita Sari",
				"jenis_kelamin" => "Pr",
				"tempat_lahir" => "Tabanan",
				"tanggal_lahir" => "1996-11-29",
				"telp_alumni" => "082237404808",
				"alamat_alumni" => "BTN Senapahan II No. 26, Br. D",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2054",
				"jabatan_terakhir" => "Staf Seksi Integrasi Pengolahan dan Diseminasi Statistik",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "199611292019012002",
				"nip_bps" => "340058885",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Putu Yogi Wigunanca",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Tabanan",
				"tanggal_lahir" => "1994-11-15",
				"telp_alumni" => "081558417994",
				"alamat_alumni" => "banjar rangdu, desa pohsanten",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2052",
				"jabatan_terakhir" => "Penugasan Statistisi Pelaksana Lanjutan Seksi Statistik Produksi",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "199411152019011001",
				"nip_bps" => "340058915",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Ni Putu Ayu Mila Dewi",
				"jenis_kelamin" => "Pr",
				"tempat_lahir" => "Karangasem",
				"tanggal_lahir" => "1992-12-28",
				"telp_alumni" => "081806595936",
				"alamat_alumni" => "Jalan Anawai no. 27",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2051",
				"jabatan_terakhir" => "Statistisi Pertama Seksi Statistik Industri",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "199212282014122001",
				"nip_bps" => "340057159",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Ratna Rosmayanti",
				"jenis_kelamin" => "Pr",
				"tempat_lahir" => "Cianjur",
				"tanggal_lahir" => "1972-10-11",
				"telp_alumni" => "085860789234",
				"alamat_alumni" => "JL PIRUS II NO. 34 BLOK 7 PERU",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2030",
				"jabatan_terakhir" => "Kepala Seksi Integrasi Pengolahan dan Diseminasi Statistik",
				"aktif_pns" => "1",
				"deskripsi" => "Tring tring",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "197210111992032001",
				"nip_bps" => "340013242",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Aris Muji Atmoko",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Karawang",
				"tanggal_lahir" => "1983-11-20",
				"telp_alumni" => " 6281381234899",
				"alamat_alumni" => "Perum Pesona Handayani Indah",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2041",
				"jabatan_terakhir" => "Statistisi Muda Seksi Statistik Sosial",
				"aktif_pns" => "1",
				"deskripsi" => "Jalan dengan kaki",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => " 198311202009021004",
				"nip_bps" => " 340050003",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Efran Feri Kriswanto",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Palembang",
				"tanggal_lahir" => "1985-02-22",
				"telp_alumni" => "085208314690",
				"alamat_alumni" => "Jl R. Sukamto Lr. Masjid No.39",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2043",
				"jabatan_terakhir" => "Staf Seksi Neraca Wilayah dan Analisis Statistik",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "198502222009021005",
				"nip_bps" => "340050005",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Husin Maulana",
				"jenis_kelamin" => "LK",
				"tempat_lahir" => "Jakarta Selatan",
				"tanggal_lahir" => "0000-00-00",
				"telp_alumni" => "",
				"alamat_alumni" => "Griya Serang Asri Blok L4/13",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2033",
				"jabatan_terakhir" => "Kepala BPS Kabupaten/Kota",
				"aktif_pns" => "1",
				"deskripsi" => "asadadassas",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "197504231996121001",
				"nip_bps" => "340015382",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Toto E Sastrasuanda",
				"jenis_kelamin" => "LK",
				"tempat_lahir" => "Cirebon",
				"tanggal_lahir" => "0000-00-00",
				"telp_alumni" => "",
				"alamat_alumni" => "Dusun Belawa I Rt 03/01",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2003",
				"jabatan_terakhir" => "Kepala Deputi Bidang Statistik Sosial",
				"aktif_pns" => "1",
				"deskripsi" => "sasasaasa",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "",
				"nip_bps" => "340003304",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Anik Triani",
				"jenis_kelamin" => "PR",
				"tempat_lahir" => "Semarang",
				"tanggal_lahir" => "0000-00-00",
				"telp_alumni" => "",
				"alamat_alumni" => "Griya Cempaka Arum Blok AA 11",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2039",
				"jabatan_terakhir" => "Statistisi Muda Seksi Statistik Pertambangan, Energi dan Konstruksi",
				"aktif_pns" => "1",
				"deskripsi" => "asadadadad",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "198103102002122002",
				"nip_bps" => "340016472",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Maya Harsanti",
				"jenis_kelamin" => "PR",
				"tempat_lahir" => "Jakarta",
				"tanggal_lahir" => "0000-00-00",
				"telp_alumni" => "",
				"alamat_alumni" => "Perum Grand Duta Cluster Jade",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2038",
				"jabatan_terakhir" => "Staf Seksi Statistik Distribusi",
				"aktif_pns" => "1",
				"deskripsi" => "ADAAADADDAD",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "198011042002122001",
				"nip_bps" => "340016479",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Lestari Utaminingsih",
				"jenis_kelamin" => "PR",
				"tempat_lahir" => "Kendal",
				"tanggal_lahir" => "1977-10-13",
				"telp_alumni" => "085641509482",
				"alamat_alumni" => "Jl. Candi Kencana IV/C.66",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2035",
				"jabatan_terakhir" => "Staf Subbagian Kepegawaian & Hukum",
				"aktif_pns" => "1",
				"deskripsi" => "Taken",
				"ig" => "lestari10",
				"fb" => "",
				"twitter" => "lestari_utami",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "197710132000022001",
				"nip_bps" => "340016072",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Hengki Eko Riyadi",
				"jenis_kelamin" => "LK",
				"tempat_lahir" => "Lubang Lor (Purworejo)",
				"tanggal_lahir" => "1978-09-03",
				"telp_alumni" => "085261660531",
				"alamat_alumni" => "Grand Serpong Residence Blok A",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2038",
				"jabatan_terakhir" => "Statistisi Madya Pejabat Fungsional",
				"aktif_pns" => "1",
				"deskripsi" => "Laper nih",
				"ig" => "iri_hengki",
				"fb" => "",
				"twitter" => "hengki01",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "197809032000121002",
				"nip_bps" => "340016113",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Eddy Prayitno",
				"jenis_kelamin" => "LK",
				"tempat_lahir" => "Bandar Lampung",
				"tanggal_lahir" => "1977-01-15",
				"telp_alumni" => "07215605102",
				"alamat_alumni" => "Jl. Purnawirawan Raya Belakang",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2035",
				"jabatan_terakhir" => "Kepala BPS Kabupaten/Kota",
				"aktif_pns" => "1",
				"deskripsi" => "Makan bang!!",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "197701151999011001",
				"nip_bps" => "340015736",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Edison Manurung",
				"jenis_kelamin" => "LK",
				"tempat_lahir" => "Tapanuli Utara",
				"tanggal_lahir" => "1962-11-10",
				"telp_alumni" => "021-7815560",
				"alamat_alumni" => "Jl.Raya Lt.Agung Tg.BaratRt.00",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"status_bekerja" => "0",
				"perkiraan_pensiun" => "2019",
				"jabatan_terakhir" => "Staf Seksi Penyiapan Statistik Perdagangan Dalam Negeri",
				"aktif_pns" => "0",
				"deskripsi" => "Ngantuk bat",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "196211101988021001",
				"nip_bps" => "340011827",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Bambang Susilo",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Blora",
				"tanggal_lahir" => "1957-04-03",
				"telp_alumni" => "",
				"alamat_alumni" => "H.Ahyar No.49 RT.006/05 13440",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2013",
				"jabatan_terakhir" => "Staf Seksi Pengolahan Statistik Pendidikan dan Kesejahteraan Sosial",
				"aktif_pns" => "0",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "195704031977121001",
				"nip_bps" => "340005601",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Hotbel Purba",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Pasir/Banjar Tongga",
				"tanggal_lahir" => "1966-06-20",
				"telp_alumni" => "081350343245",
				"alamat_alumni" => "Jl. Pusat Pemerintahan",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2024",
				"jabatan_terakhir" => "Kepala BPS Kabupaten/Kota",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "196606201986031001",
				"nip_bps" => "340011571",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Edison Situmorang",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Simarsoituruk",
				"tanggal_lahir" => "1966-11-26",
				"telp_alumni" => "082347774666",
				"alamat_alumni" => "A W syahrani 4 Rt 23 Sempaja",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2024",
				"jabatan_terakhir" => "Kepala Seksi Statistik Sosial",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "196611261988021001",
				"nip_bps" => "340011786",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Chatarina Budi Anggarini",
				"jenis_kelamin" => "Pr",
				"tempat_lahir" => "Bantul",
				"tanggal_lahir" => "1969-04-29",
				"telp_alumni" => "089610147898",
				"alamat_alumni" => "Melikan Lor RT 04 Gandekan Ban",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2027",
				"jabatan_terakhir" => "Kepala Seksi Statistik Keuangan Dan Harga Produsen",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "196904291989022001",
				"nip_bps" => "340012122",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Muhammad Dedy",
				"jenis_kelamin" => "LK",
				"tempat_lahir" => "Palembang",
				"tanggal_lahir" => "1978-08-05",
				"telp_alumni" => "081377900322",
				"alamat_alumni" => "Jl. Sambu No. 33",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2036",
				"jabatan_terakhir" => "Kepala BPS Kabupaten/Kota",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "197808052000121001",
				"nip_bps" => "340016240",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Ayu Setiawaty",
				"jenis_kelamin" => "PR",
				"tempat_lahir" => "Jakarta Barat",
				"tanggal_lahir" => "1977-05-09",
				"telp_alumni" => "Jakarta Barat",
				"alamat_alumni" => "PERUMAHAN DUKUH ZAMRUD BLOK N7",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2035",
				"jabatan_terakhir" => "Penugasan Statistisi Pertama Seksi Statistik Distribusi",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "197705092000122007",
				"nip_bps" => "340016241",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Shanti Kartika Astrilestari",
				"jenis_kelamin" => "PR",
				"tempat_lahir" => "Surabaya",
				"tanggal_lahir" => "1979-04-26",
				"telp_alumni" => "082181923897",
				"alamat_alumni" => "Perum Ragom Mufakat I Blok F-5",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2037",
				"jabatan_terakhir" => "Kepala Seksi Neraca Wilayah dan Analisis Statistik",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "197904262000122001",
				"nip_bps" => "340016242",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Bambang Pamungkas",
				"jenis_kelamin" => "LK",
				"tempat_lahir" => "Semarang",
				"tanggal_lahir" => "1979-09-17",
				"telp_alumni" => "081355103999",
				"alamat_alumni" => "Jl Kredit Blok B 5 No 13",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2037",
				"jabatan_terakhir" => "Kepala BPS Kabupaten/Kota",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "197909172000121003",
				"nip_bps" => "340016243",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Johanes Supranto",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Semarang",
				"tanggal_lahir" => "1939-05-22",
				"telp_alumni" => "",
				"alamat_alumni" => "Jl. Kejaksaan Raya No. 23 Kreo C",
				"kota" => "",
				"provinsi" => "DKI Jakarta",
				"negara" => "Indonesia",
				"status_bekerja" => "0",
				"perkiraan_pensiun" => "2004",
				"jabatan_terakhir" => "Kepala K.S Tk. I (Tipe A)",
				"aktif_pns" => "0",
				"deskripsi" => "Jangan Menyerah",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "",
				"nip_bps" => "340000423",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "1",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Gita Devi Asyarita",
				"jenis_kelamin" => "Pr",
				"tempat_lahir" => "Bekasi",
				"tanggal_lahir" => "1994-08-05",
				"telp_alumni" => "6281319546221",
				"alamat_alumni" => "Desa Daruba",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2052",
				"jabatan_terakhir" => "Statistisi Pertama Seksi Statistik Distribusi",
				"aktif_pns" => "1",
				"deskripsi" => "Bersakit-sakit dahulu, bersenang-senangnya gak tau kapan",
				"ig" => "gitaasy_",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "199408052017012001",
				"nip_bps" => "340058000",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "1",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Galang Retno Winarko",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Blitar",
				"tanggal_lahir" => "1990-10-22",
				"telp_alumni" => "6282299649735",
				"alamat_alumni" => "RT 4 RW 3, Desa Panggungrejo, Kecamatan Panggungrejo",
				"kota" => "Blitar",
				"provinsi" => "Jawa Timur",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2048",
				"jabatan_terakhir" => "Staf Seksi Integrasi Pengolahan Data",
				"aktif_pns" => "1",
				"deskripsi" => "WOW Amazing",
				"ig" => "galang_winarko",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "199010222017011001",
				"nip_bps" => "340057999",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "1",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Timbang Sirait",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Labuhan Batu",
				"tanggal_lahir" => "1973-12-27",
				"telp_alumni" => "628179719667",
				"alamat_alumni" => "Puri Bintara Regency Blok K-19",
				"kota" => "Jakarta Timur",
				"provinsi" => "DKI Jakarta",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2039",
				"jabatan_terakhir" => "Lektor Tenaga Fungsional STIS",
				"aktif_pns" => "1",
				"deskripsi" => "Statmat jaya",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "197312272000031002",
				"nip_bps" => "340016106",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "1",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Khaerul Anwar",
				"jenis_kelamin" => "LK",
				"tempat_lahir" => "Demak",
				"tanggal_lahir" => "1970-03-29",
				"telp_alumni" => "081228439121",
				"alamat_alumni" => "Perum Griya Utama Permai Blok",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2028",
				"jabatan_terakhir" => "Kepala Seksi Integrasi Pengolahan dan Diseminasi Statistik",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "197003291991021001",
				"nip_bps" => "340012773",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Achmad Rifai",
				"jenis_kelamin" => "LK",
				"tempat_lahir" => "Jakarta Utara",
				"tanggal_lahir" => "1974-12-05",
				"telp_alumni" => "082221518394",
				"alamat_alumni" => "Jl. Kranji No. 493",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2033",
				"jabatan_terakhir" => "Kepala Seksi Integrasi Pengolahan dan Diseminasi Statistik",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "197412052000031001",
				"nip_bps" => "340016107",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Apriliya Puput Nadea",
				"jenis_kelamin" => "PR",
				"tempat_lahir" => "Klaten",
				"tanggal_lahir" => "1989-04-06",
				"telp_alumni" => "085647331647",
				"alamat_alumni" => "Gg Spoor Dalam IV no 12",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2047",
				"jabatan_terakhir" => "Staf Seksi Jasa Perpustakaan",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "198904062012112001",
				"nip_bps" => "340055736",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Arini Ismiati",
				"jenis_kelamin" => "PR",
				"tempat_lahir" => "Malang",
				"tanggal_lahir" => "1979-12-20",
				"telp_alumni" => "081215927271",
				"alamat_alumni" => "Jl. Batok GG III no.5",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2038",
				"jabatan_terakhir" => "Statistisi Muda Seksi Statistik Produksi",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "197912202003122006",
				"nip_bps" => "340017013",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Dea Venditama",
				"jenis_kelamin" => "LK",
				"tempat_lahir" => "Bantul",
				"tanggal_lahir" => "1991-06-02",
				"telp_alumni" => "6282292146507",
				"alamat_alumni" => "Otista",
				"kota" => "Pusat",
				"provinsi" => "DKI Jakarta",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2049",
				"jabatan_terakhir" => "Pranata Komputer Pertama Seksi Pemantauan dan Evaluasi Publikasi",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "199106022014101001",
				"nip_bps" => "340056757",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Delly Rakasiwi",
				"jenis_kelamin" => "LK",
				"tempat_lahir" => "Jakarta",
				"tanggal_lahir" => "1991-03-05",
				"telp_alumni" => "",
				"alamat_alumni" => "Ki Hajar DewantaraRT 01 RW 06",
				"kota" => "Palangkaraya",
				"provinsi" => "Kalimantan Tengah",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2049",
				"jabatan_terakhir" => "Pranata Komputer Pertama Seksi Jaringan dan Rujukan Statistik",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "199103052014101002",
				"nip_bps" => "340056758",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Dhoni Eko Wahyu Nugroho",
				"jenis_kelamin" => "LK",
				"tempat_lahir" => "Kediri",
				"tanggal_lahir" => "1991-07-28",
				"telp_alumni" => "",
				"alamat_alumni" => "Jl. Kebon Nanas Utara No 10 Ja",
				"kota" => "Pusat",
				"provinsi" => "DKI Jakarta",
				"negara" => "Indonesia",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2049",
				"jabatan_terakhir" => "Pranata Komputer Pertama Seksi Pengemasan Informasi Statistik",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "199107282014101001",
				"nip_bps" => "340056759",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Poltak Sutrisno Siahaan",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Tebing Tinggi",
				"tanggal_lahir" => "1952-08-06",
				"telp_alumni" => "",
				"alamat_alumni" => "Jl. Asrama Komplek Bumi AsriBl",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2012",
				"jabatan_terakhir" => "Staf MPP",
				"aktif_pns" => "0",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "195208061975031001",
				"nip_bps" => "340004375",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Weni Lidya Sukma",
				"jenis_kelamin" => "Pr",
				"tempat_lahir" => "Padang Pariaman",
				"tanggal_lahir" => "1989-09-12",
				"telp_alumni" => "085263662023",
				"alamat_alumni" => "jl. mandor dami 2 perumahan fe",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2047",
				"jabatan_terakhir" => "Penugasan Statistisi Pelaksana Lanjutan Seksi Pengolahan Statistik Ketenagakerjaan",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "198909122012112001",
				"nip_bps" => "340055951",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Tri Hayuni Syardi",
				"jenis_kelamin" => "Pr",
				"tempat_lahir" => "Padang",
				"tanggal_lahir" => "1990-10-30",
				"telp_alumni" => "081281060452",
				"alamat_alumni" => "Komplek Mawar Putih Blok L No.",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2048",
				"jabatan_terakhir" => "Kepala Seksi Integrasi Pengolahan dan Diseminasi Statistik",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "199010302012112001",
				"nip_bps" => "340055938",
				"foto_profil" => "components/icon/PR-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Subuh Sukmono Putro",
				"jenis_kelamin" => "Lk",
				"tempat_lahir" => "Sragen",
				"tanggal_lahir" => "1975-03-15",
				"telp_alumni" => "081329278642",
				"alamat_alumni" => "Graha Surya No IC",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2033",
				"jabatan_terakhir" => "Kepala Seksi Statistik Sosial",
				"aktif_pns" => "1",
				"deskripsi" => "",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "197503151996121001",
				"nip_bps" => "340015332",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
			[
				"nama" => "Sigit Purnomo",
				"jenis_kelamin" => "LK",
				"tempat_lahir" => "Kulon Progo",
				"tanggal_lahir" => "1965-02-17",
				"telp_alumni" => "081288378366",
				"alamat_alumni" => "Puri Citayam Permai Blok B-10",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"status_bekerja" => "1",
				"perkiraan_pensiun" => "2023",
				"jabatan_terakhir" => "Kepala Bagian Penyusunan Rencana",
				"aktif_pns" => "1",
				"deskripsi" => "mantap",
				"ig" => "",
				"fb" => "",
				"twitter" => "",
				"linkedin" => "",
				"gscholar" => "",
				"nip" => "196502171988021001",
				"nip_bps" => "340011821",
				"foto_profil" => "components/icon/Lk-icon.svg",
				"cttl" => "0",
				"calamat" => "0",
				"cpendidikan" => "0",
				"cprestasi" => "0",
			],
		];
		$this->db->table('alumni')->insertBatch($data);

		// $data = [
		// 	'id_alumni'          => "1",
		// 	'nama'               => "Dummy_dummy",
		// 	'jenis_kelamin'      => $faker->randomElement($array = array('Lk', 'Pr')),
		// 	'tempat_lahir'       => $faker->city,
		// 	'tanggal_lahir'      => $faker->date($format = 'Y-m-d', $max = 'now'),
		// 	'telp_alumni'        => $faker->phoneNumber,
		// 	'alamat_alumni'      => $faker->address,
		// 	'status_bekerja'     => $faker->boolean,
		// 	'perkiraan_pensiun'  => $faker->year,
		// 	'jabatan_terakhir'   => $faker->jobTitle,
		// 	'aktif_pns'          => $faker->boolean,
		// 	'deskripsi'          => $faker->text,
		// 	'email'				 => $faker->email,
		// 	'ig'          		 => "dummy_igza__",
		// 	'twitter'          	 => "Dummy__",
		// 	'nip'          	 	 => "198109262004122002",
		// 	'nip_bps'          	 => "301820912",
		// 	'foto_profil'      	 => $faker->randomElement($array = array('Lk', 'Pr'))."/default.svg"
		// ];
		// $this->db->table('alumni')->insert($data);

		$data = [
			[
				"nama_instansi" => "BPS Dummy",
				"kota" => "Manado",
				"provinsi" => "Lampung",
				"negara" => "Albania",
				"alamat_instansi" => "Ki. Acordion No. 70, Probolinggo 66519, KalUt",
				"telp_instansi" => "0859 3699 927",
				"faks_instansi" => "0809 083 024",
				"email_instansi" => "yunita57@gmail.com",
			],
			[
				"nama_instansi" => "BPS Pusat",
				"kota" => "Jakarta Pusat",
				"provinsi" => "DKI Jakarta",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Dr. Sutomo 6-8",
				"telp_instansi" => "(62-21) 3841195",
				"faks_instansi" => "(62-21) 3857046",
				"email_instansi" => "bpshq@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kota Semarang",
				"kota" => "Semarang",
				"provinsi" => "Jawa Tengah",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Inspeksi Kali Semarang No.1",
				"telp_instansi" => "0243546413",
				"faks_instansi" => "",
				"email_instansi" => "bps3374@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Tabanan",
				"kota" => "Tabanan",
				"provinsi" => "Bali",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Pahlawan No 1B",
				"telp_instansi" => "0361811571",
				"faks_instansi" => "",
				"email_instansi" => "bps5102@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Karawang",
				"kota" => "Karawang",
				"provinsi" => "Jawa Barat",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Cakradireja No.36",
				"telp_instansi" => "0267402250",
				"faks_instansi" => "",
				"email_instansi" => "kabkarawang@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Lamongan",
				"kota" => "Lamongan",
				"provinsi" => "Jawa Timur",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Veteran 185 Lamongan-62218",
				"telp_instansi" => "(0322) 321339",
				"faks_instansi" => "(0322) 321339",
				"email_instansi" => "bps3524@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Provinsi Lampung",
				"kota" => "Bandar Lampung",
				"provinsi" => "Lampung",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Basuki Rahmat No 54",
				"telp_instansi" => "(62-721) 482909",
				"faks_instansi" => "(62-721) 484329",
				"email_instansi" => "bps1800@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Tegal",
				"kota" => "Tegal",
				"provinsi" => "Jawa Tengah",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl Ade Irma Suryani No 1 Slawi",
				"telp_instansi" => "(0283) 4561190",
				"faks_instansi" => "(0283) 4561190",
				"email_instansi" => "bps3328@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Provinsi DKI Jakarta",
				"kota" => "Jakarta Pusat",
				"provinsi" => "Jakarta",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Salemba Tengah No. 36-38 Paseban Senen",
				"telp_instansi" => "(021) 31928493",
				"faks_instansi" => "(021) 3152004",
				"email_instansi" => "bps3100@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Provinsi Jawa Barat",
				"kota" => "Bandung",
				"provinsi" => "Jawa Barat",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. PHH. Mustofa No. 43 Bandung 40124",
				"telp_instansi" => "+62 22 7272595",
				"faks_instansi" => "+62 22 7213572",
				"email_instansi" => "bps3200@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Indragiri Hilir",
				"kota" => "Indragiri Hilir",
				"provinsi" => "Riau",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Praja Sakti (Bunga) No. 11 Tembilahan Hilir, Tembilahan. ",
				"telp_instansi" => " (0768) 22489",
				"faks_instansi" => " (0768) 22489",
				"email_instansi" => "bps1403@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Provinsi Kalimantan Selatan",
				"kota" => "Palangkaraya",
				"provinsi" => "Kalimantan Tengah",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Kapt. Piere Tendean No 6 Palangka Raya 73112 Indonesia",
				"telp_instansi" => " (0536) 322 8105",
				"faks_instansi" => " (0536) 322 8105",
				"email_instansi" => "kalteng@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Provinsi Nusa Tenggara Timur",
				"kota" => "Kupang",
				"provinsi" => "Nusa Tenggara Timur",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. R. Suprapto No. 5",
				"telp_instansi" => "(0380) 8554535",
				"faks_instansi" => "(0380) 8550136",
				"email_instansi" => "ntt@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kota Pariaman",
				"kota" => "Pariaman",
				"provinsi" => "Sumatera Barat",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Sentot Ali Basa",
				"telp_instansi" => "(0751) 93785",
				"faks_instansi" => "(0751) 93780",
				"email_instansi" => "pariaman@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Boyolali",
				"kota" => "Boyolali",
				"provinsi" => "Jawa Tengah",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Raya Boyolali-Semarang No.Km. 2",
				"telp_instansi" => "(0276) 323772",
				"faks_instansi" => "(0276) 323701",
				"email_instansi" => "boyolali@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Garut",
				"kota" => "Garut",
				"provinsi" => "Jawa Barat",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Pembangunan No.222, Sukagalih, Kec. Tarogong Kidul",
				"telp_instansi" => "233273",
				"faks_instansi" => "020234873432",
				"email_instansi" => "bpsgarut@gmail.com",
			],
			[
				"nama_instansi" => "BPS Kabupaten Musi Banyuasin",
				"kota" => "Musi Banyuasin",
				"provinsi" => "Sumatera Selatan",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Merdeka No.531, Kayu Ara, Sekayu",
				"telp_instansi" => "0001234",
				"faks_instansi" => "02025678",
				"email_instansi" => "bpsmusibanyuasin@gmail.com",
			],
			[
				"nama_instansi" => "BPS Kabupaten Lebak",
				"kota" => "Lebak",
				"provinsi" => "Banten",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Jendral Sudirman No.807, Narimbang Mulia, Kec. Rangkasbitung, Kabupaten Lebak, Banten 42315",
				"telp_instansi" => "(62-252) 5554673",
				"faks_instansi" => "",
				"email_instansi" => "bps3602@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kota Tangerang",
				"kota" => "Tangerang",
				"provinsi" => "Banten",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. RHM Noer Radji No. 28 Gerendeng Tangerang",
				"telp_instansi" => "(62-21) 55792858",
				"faks_instansi" => "(62-21) 55796910",
				"email_instansi" => "bps3671@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Provinsi Jawa Tengah",
				"kota" => "Semarang",
				"provinsi" => "Jawa Tengah",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Pahlawan No.6, Pleburan, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50241",
				"telp_instansi" => "024 - 8412802",
				"faks_instansi" => "024 - 8311195",
				"email_instansi" => "bps3300@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Pringsewu",
				"kota" => "Pringsewu",
				"provinsi" => "Lampung",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Raya Gading Rejo KM.33 Wonodadi, Gading Rejo 35372",
				"telp_instansi" => "(62-729) 7330811",
				"faks_instansi" => "",
				"email_instansi" => "bps1810@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kota Jakarta Selatan",
				"kota" => "Jakarta Selatan",
				"provinsi" => "DKI Jakarta",
				"negara" => "Indonesia",
				"alamat_instansi" => "Komplek Walikota Jakarta Selatan Blok A 15th Floor, JL. Prapanca Raya, No. 9, Kebayoran Baru, RT.2/RW.3, Pulo, Kec. Kby. Baru, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12160",
				"telp_instansi" => "(021) 72792576",
				"faks_instansi" => "(021) 27872812",
				"email_instansi" => "bps3171@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Indramayu",
				"kota" => "Indramayu",
				"provinsi" => "Jawa Barat",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Golf No. 4 Indramayu, Jawa Barat - Indonesia",
				"telp_instansi" => "+62 234 272880",
				"faks_instansi" => "+62 234 272880",
				"email_instansi" => "bps3212@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Bintan",
				"kota" => "Bintan",
				"provinsi" => "Kepulauan Riau",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Tata Bumi, Ceruk Ijuk, Toapaya, Bintan, Kepulauan Riau",
				"telp_instansi" => " (0771) 3300 700",
				"faks_instansi" => "",
				"email_instansi" => "bps2102@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kota Surabaya",
				"kota" => "Kota Surabaya",
				"provinsi" => "Jawa Timur",
				"negara" => "",
				"alamat_instansi" => "Jl. A. Yani 152 E Surabaya 60231 Jawa Timur Indonesia",
				"telp_instansi" => "(62-31) 82516020",
				"faks_instansi" => "(62-31) 8296691",
				"email_instansi" => "bps3578@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Minahasa",
				"kota" => "Minahasa",
				"provinsi" => "Sulawesi Utara",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Dotulolong Lasut, Tondano Timur, Minahasa",
				"telp_instansi" => "(0431)321155",
				"faks_instansi" => "(0431)321155",
				"email_instansi" => " bps7102@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Jawa Timur",
				"kota" => "Surabaya",
				"provinsi" => "Jawa Timur",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Raya Kendangsari Industri N0.34",
				"telp_instansi" => "081213869409",
				"faks_instansi" => "62913857000",
				"email_instansi" => "tpramono11@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Bangka Selatan",
				"kota" => "Bangka Selatan",
				"provinsi" => "Bangka Belitung",
				"negara" => "Indonesia",
				"alamat_instansi" => "",
				"telp_instansi" => "(0718) 4220039",
				"faks_instansi" => "",
				"email_instansi" => "bps1905@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Tomohon",
				"kota" => "Tomohon",
				"provinsi" => "Sulawesi Utara",
				"negara" => "Indonesia",
				"alamat_instansi" => "JL. Nimawanua, Lansot, Lansot, Tomohon Sel., Kota Tomohon, Sulawesi Utara",
				"telp_instansi" => "0431) 3159904",
				"faks_instansi" => "",
				"email_instansi" => "bps7173@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Sorong Selatan",
				"kota" => "Sorong Selatan",
				"provinsi" => "Papua Barat",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jalan Teminabuan-Ayamaru",
				"telp_instansi" => "",
				"faks_instansi" => "",
				"email_instansi" => "bps9106@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Sulawesi Tenggara",
				"kota" => "Kendari",
				"provinsi" => "Sulawesi Tenggara",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Boulevard No. 1 Kendari Sulawesi Tenggara",
				"telp_instansi" => "(0401) 3135363",
				"faks_instansi" => "0401-3122355",
				"email_instansi" => "bps7400@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Sukabumi",
				"kota" => "Sukabumi",
				"provinsi" => "Jawa Barat",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Raya Karangtengah Km 14 No 52 Cibadak Sukabumi 43351",
				"telp_instansi" => "0266536953",
				"faks_instansi" => "0653536949",
				"email_instansi" => "bps3202@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Gunungkidul",
				"kota" => "Gunungkidul",
				"provinsi" => "Jawa Tengah",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Pemuda 19A Baleharjo Wonosari 55811",
				"telp_instansi" => "0274394180",
				"faks_instansi" => "0274394181",
				"email_instansi" => "bps3403@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Ogan Ilir",
				"kota" => "Prabumulih",
				"provinsi" => "Sumatera Selatan",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Palembang-Prabumulih Km 33 Desa Tanjung Pering 30813 Indralaya",
				"telp_instansi" => "0711581713",
				"faks_instansi" => "0711581713",
				"email_instansi" => "bps1610@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Paser",
				"kota" => "Paser",
				"provinsi" => "Kalimantan Timur",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Gajah Mada No.76, Tanah Grogot",
				"telp_instansi" => "(0543)21219",
				"faks_instansi" => "(0543)21219",
				"email_instansi" => "bps6401@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kota Samarinda",
				"kota" => "Samarinda",
				"provinsi" => "Kalimantan Timur",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Kyai Haji Ahmad Dahlan No.33, Sungai Pinang Luar",
				"telp_instansi" => "(0543)21219",
				"faks_instansi" => "(0543)21219",
				"email_instansi" => "bps6401@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Provinsi Daerah Istimewa Yogyakarta",
				"kota" => "Bantul",
				"provinsi" => "Daerah Istimewa Yogyakar",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jalan Lingkar Selatan, Tamantirto, Kasihan, Geblagan, Tamantirto",
				"telp_instansi" => "0274-4342234",
				"faks_instansi" => "0274-4342230",
				"email_instansi" => "pst3400@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kab Empat Lawang",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Lintas Sumatera No. 35 Kecamatan Tebing Tinggi Kabupaten Empat Lawang Sumatera Selatan",
				"telp_instansi" => "070221674",
				"faks_instansi" => "070221674",
				"email_instansi" => "bps1611@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kota Bekasi",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Rawa Tembaga I, No. 6, Bekasi",
				"telp_instansi" => "02188953987",
				"faks_instansi" => "02188953987",
				"email_instansi" => "bps3275@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kab Lampung Selatan",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Mustafa Kemal No. 24 Kalianda, Lampung Selatan - Lampung",
				"telp_instansi" => "0727322241 ",
				"faks_instansi" => "0727322241 ",
				"email_instansi" => "bps1803@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kab Tasikmalaya",
				"kota" => "",
				"provinsi" => "",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jalan Raya Timur Singaparna km 4 Cintaraja Singaparna Tasikmalaya",
				"telp_instansi" => "0265549281",
				"faks_instansi" => "0265549253",
				"email_instansi" => "bps3206@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Pulau Morotai",
				"kota" => "Pulau Morotai",
				"provinsi" => "Maluku Utara",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jln. Hi. Ahmad Syukur, Kec. Morotai Selatan, Pulau Morotai-Maluku Utara, 97771",
				"telp_instansi" => "(0923) 2221133",
				"faks_instansi" => "",
				"email_instansi" => "bps8207@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Provinsi Maluku Utara",
				"kota" => "Ternate",
				"provinsi" => "Maluku Utara",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Stadion No 65 Ternate 97712",
				"telp_instansi" => "(0921) 3127878",
				"faks_instansi" => "(0921) 3126301",
				"email_instansi" => "bps8200@bps.go.id",
			],
			[
				"nama_instansi" => "Politeknik Statistika STIS",
				"kota" => "Jakarta Timur",
				"provinsi" => "DKI Jakarta",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Otto Iskandardinata No. 64C",
				"telp_instansi" => "(021) 8508812",
				"faks_instansi" => "8197577",
				"email_instansi" => "info@stis.ac.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten/Kota Bandung",
				"kota" => "Bandung",
				"provinsi" => "Jawa Barat",
				"negara" => "Indonesia",
				"alamat_instansi" => "",
				"telp_instansi" => "",
				"faks_instansi" => "",
				"email_instansi" => "",
			],
			[
				"nama_instansi" => "BPS Kabupaten Aceh Singkil",
				"kota" => "Aceh Singkil",
				"provinsi" => "Aceh",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. H. Sayuthi No. 2 Pulo Sarok",
				"telp_instansi" => "(0658) 21268",
				"faks_instansi" => "21268",
				"email_instansi" => "bps1102@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Rembang",
				"kota" => "Rembang",
				"provinsi" => "Jawa Tengah",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Pemuda Km. 1",
				"telp_instansi" => "0295691040",
				"faks_instansi" => "0295691040",
				"email_instansi" => "bps3317@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Cilacap",
				"kota" => "Cilacap",
				"provinsi" => "Jawa Tengah",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jalan Dr. Soetomo No. 16A",
				"telp_instansi" => "0282534328",
				"faks_instansi" => "0282535011",
				"email_instansi" => "bps3301@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Klaten",
				"kota" => "Klaten",
				"provinsi" => "Jawa Tengah",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Merapi No. 6",
				"telp_instansi" => "62272321689",
				"faks_instansi" => "",
				"email_instansi" => "bps3310@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kota Malang",
				"kota" => "Malang",
				"provinsi" => "Jawa Timur",
				"negara" => "Indonesia",
				"alamat_instansi" => "Jl. Janti Barat No. 47",
				"telp_instansi" => "0341801164",
				"faks_instansi" => "0341805871",
				"email_instansi" => "bps3573@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kota Banjarmasin",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"alamat_instansi" => "Jalan Gatot Subroto No. 5 Banjarmasin 70235",
				"telp_instansi" => "(0511) 6773031",
				"faks_instansi" => "(0511) 6773032",
				"email_instansi" => "bps6371@gmail.com",
			],
			[
				"nama_instansi" => "BPS Provinsi Riau",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"alamat_instansi" => "Jl. Pattimura No. 12 Pekanbaru - Riau, Indonesia",
				"telp_instansi" => "(62-761) 23042",
				"faks_instansi" => "(62-761) 21336",
				"email_instansi" => "riau@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Tanjung Jabung Barat",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"alamat_instansi" => "Jl. Prof.Dr. Sri Soedewi MS, SH.-Kuala Tungkal, Jambi",
				"telp_instansi" => "(0742) 21738",
				"faks_instansi" => "",
				"email_instansi" => "bps1507@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Provinsi Sulawesi Utara",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"alamat_instansi" => "Jl. 17 Agustus Manado 95119",
				"telp_instansi" => "(0431) 847044",
				"faks_instansi" => "(0431) 862204",
				"email_instansi" => "mailto:sulut@bps.go.id",
			],
			[
				"nama_instansi" => "BPS Kabupaten Cirebon",
				"kota" => "",
				"provinsi" => "",
				"negara" => "",
				"alamat_instansi" => "Jl. Sunan Kalijaga No.4 Sumber-Cirebon 45611",
				"telp_instansi" => "+62 231 321445",
				"faks_instansi" => "+62 231 321445",
				"email_instansi" => "bps3209@bps.go.id",
			],
		];
		$this->db->table('tempat_kerja')->insertBatch($data);

		// $data = [
		// 	'nama_instansi' 	=> "BPS Dummy",
		// 	'kota'      	 	=> $faker->city,
		// 	'provinsi'      	=> $faker->state,
		// 	'negara'      		=> $faker->country,
		// 	'alamat_instansi' 	=> $faker->address,
		// 	'telp_instansi' 	=> $faker->phoneNumber,
		// 	'faks_instansi' 	=> $faker->phoneNumber,
		// 	'email_instansi' 	=> $faker->freeEmail,
		// ];
		// $this->db->table('tempat_kerja')->insert($data);

		$data = [
			[
				"id_alumni" => 1,
				"id_tempat_kerja" => 2,
			],
			[
				"id_alumni" => 2,
				"id_tempat_kerja" => 2,
			],
			[
				"id_alumni" => 3,
				"id_tempat_kerja" => 5,
			],
			[
				"id_alumni" => 4,
				"id_tempat_kerja" => 4,
			],
			[
				"id_alumni" => 5,
				"id_tempat_kerja" => 3,
			],
			[
				"id_alumni" => 6,
				"id_tempat_kerja" => 55,
			],
			[
				"id_alumni" => 7,
				"id_tempat_kerja" => 13,
			],
			[
				"id_alumni" => 8,
				"id_tempat_kerja" => 2,
			],
			[
				"id_alumni" => 9,
				"id_tempat_kerja" => 52,
			],
			[
				"id_alumni" => 10,
				"id_tempat_kerja" => 53,
			],
			[
				"id_alumni" => 11,
				"id_tempat_kerja" => 2,
			],
			[
				"id_alumni" => 12,
				"id_tempat_kerja" => 54,
			],
			[
				"id_alumni" => 13,
				"id_tempat_kerja" => 22,
			],
			[
				"id_alumni" => 14,
				"id_tempat_kerja" => 23,
			],
			[
				"id_alumni" => 15,
				"id_tempat_kerja" => 24,
			],
			[
				"id_alumni" => 16,
				"id_tempat_kerja" => 25,
			],
			[
				"id_alumni" => 17,
				"id_tempat_kerja" => 2,
			],
			[
				"id_alumni" => 18,
				"id_tempat_kerja" => 7,
			],
			[
				"id_alumni" => 19,
				"id_tempat_kerja" => 10,
			],
			[
				"id_alumni" => 20,
				"id_tempat_kerja" => 2,
			],
			[
				"id_alumni" => 21,
				"id_tempat_kerja" => 28,
			],
			[
				"id_alumni" => 22,
				"id_tempat_kerja" => 29,
			],
			[
				"id_alumni" => 23,
				"id_tempat_kerja" => 30,
			],
			[
				"id_alumni" => 24,
				"id_tempat_kerja" => 31,
			],
			[
				"id_alumni" => 25,
				"id_tempat_kerja" => 32,
			],
			[
				"id_alumni" => 26,
				"id_tempat_kerja" => 33,
			],
			[
				"id_alumni" => 27,
				"id_tempat_kerja" => 34,
			],
			[
				"id_alumni" => 28,
				"id_tempat_kerja" => 18,
			],
			[
				"id_alumni" => 29,
				"id_tempat_kerja" => 2,
			],
			[
				"id_alumni" => 30,
				"id_tempat_kerja" => 10,
			],
			[
				"id_alumni" => 31,
				"id_tempat_kerja" => 19,
			],
			[
				"id_alumni" => 32,
				"id_tempat_kerja" => 20,
			],
			[
				"id_alumni" => 33,
				"id_tempat_kerja" => 2,
			],
			[
				"id_alumni" => 34,
				"id_tempat_kerja" => 21,
			],
			[
				"id_alumni" => 35,
				"id_tempat_kerja" => 2,
			],
			[
				"id_alumni" => 36,
				"id_tempat_kerja" => 2,
			],
			[
				"id_alumni" => 37,
				"id_tempat_kerja" => 35,
			],
			[
				"id_alumni" => 38,
				"id_tempat_kerja" => 36,
			],
			[
				"id_alumni" => 39,
				"id_tempat_kerja" => 37,
			],
			[
				"id_alumni" => 40,
				"id_tempat_kerja" => 38,
			],
			[
				"id_alumni" => 41,
				"id_tempat_kerja" => 39,
			],
			[
				"id_alumni" => 42,
				"id_tempat_kerja" => 40,
			],
			[
				"id_alumni" => 43,
				"id_tempat_kerja" => 41,
			],
			[
				"id_alumni" => 44,
				"id_tempat_kerja" => 2,
			],
			[
				"id_alumni" => 45,
				"id_tempat_kerja" => 42,
			],
			[
				"id_alumni" => 46,
				"id_tempat_kerja" => 43,
			],
			[
				"id_alumni" => 47,
				"id_tempat_kerja" => 44,
			],
			[
				"id_alumni" => 48,
				"id_tempat_kerja" => 47,
			],
			[
				"id_alumni" => 49,
				"id_tempat_kerja" => 48,
			],
			[
				"id_alumni" => 50,
				"id_tempat_kerja" => 49,
			],
			[
				"id_alumni" => 51,
				"id_tempat_kerja" => 50,
			],
			[
				"id_alumni" => 52,
				"id_tempat_kerja" => 2,
			],
			[
				"id_alumni" => 53,
				"id_tempat_kerja" => 2,
			],
			[
				"id_alumni" => 54,
				"id_tempat_kerja" => 12,
			],
			[
				"id_alumni" => 55,
				"id_tempat_kerja" => 13,
			],
			[
				"id_alumni" => 56,
				"id_tempat_kerja" => 2,
			],
			[
				"id_alumni" => 57,
				"id_tempat_kerja" => 14,
			],
			[
				"id_alumni" => 58,
				"id_tempat_kerja" => 15,
			],
			[
				"id_alumni" => 59,
				"id_tempat_kerja" => 17,
			],
		];
		$this->db->table('alumni_tempat_kerja')->insertBatch($data);

		// $data = [
		// 	'id_alumni'       => "1",
		// 	'id_tempat_kerja' => 1,
		// ];
		// $this->db->table('alumni_tempat_kerja')->insert($data);

		$data = [
			[
				"jenjang" => "D-III",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1986",
				"tahun_masuk" => "1983",
				"angkatan" => 25,
				"id_alumni" => 2,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2002",
				"tahun_masuk" => "1999",
				"angkatan" => 40,
				"id_alumni" => 2,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1986",
				"tahun_masuk" => "",
				"angkatan" => 25,
				"id_alumni" => 3,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1986",
				"tahun_masuk" => "",
				"angkatan" => 25,
				"id_alumni" => 4,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1986",
				"tahun_masuk" => "",
				"angkatan" => 25,
				"id_alumni" => 5,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1975",
				"tahun_masuk" => "1972",
				"angkatan" => 14,
				"id_alumni" => 55,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2011",
				"tahun_masuk" => "2007",
				"angkatan" => 14,
				"id_alumni" => 56,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2011",
				"tahun_masuk" => "2007",
				"angkatan" => 49,
				"id_alumni" => 57,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1966",
				"tahun_masuk" => "",
				"angkatan" => 6,
				"id_alumni" => 29,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2002",
				"tahun_masuk" => "",
				"angkatan" => 40,
				"id_alumni" => 30,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2002",
				"tahun_masuk" => "",
				"angkatan" => 40,
				"id_alumni" => 31,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "1998",
				"tahun_masuk" => "",
				"angkatan" => 37,
				"id_alumni" => 13,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2001",
				"tahun_masuk" => "",
				"angkatan" => 39,
				"id_alumni" => 13,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "1998",
				"tahun_masuk" => "",
				"angkatan" => 37,
				"id_alumni" => 14,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2013",
				"tahun_masuk" => "",
				"angkatan" => 51,
				"id_alumni" => 15,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2013",
				"tahun_masuk" => "",
				"angkatan" => 51,
				"id_alumni" => 16,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1985",
				"tahun_masuk" => "",
				"angkatan" => 24,
				"id_alumni" => 17,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2002",
				"tahun_masuk" => "",
				"angkatan" => 40,
				"id_alumni" => 17,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1985",
				"tahun_masuk" => "",
				"angkatan" => 24,
				"id_alumni" => 18,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1992",
				"tahun_masuk" => "1989",
				"angkatan" => 31,
				"id_alumni" => 21,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2018",
				"tahun_masuk" => "2014",
				"angkatan" => 56,
				"id_alumni" => 22,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2018",
				"tahun_masuk" => "2014",
				"angkatan" => 56,
				"id_alumni" => 23,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2014",
				"tahun_masuk" => "2010",
				"angkatan" => 52,
				"id_alumni" => 24,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2008",
				"tahun_masuk" => "2004",
				"angkatan" => 46,
				"id_alumni" => 25,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2008",
				"tahun_masuk" => "2004",
				"angkatan" => 46,
				"id_alumni" => 26,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2008",
				"tahun_masuk" => "2004",
				"angkatan" => 46,
				"id_alumni" => 27,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2003",
				"tahun_masuk" => "2002",
				"angkatan" => 41,
				"id_alumni" => 32,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "1999",
				"tahun_masuk" => "1996",
				"angkatan" => 38,
				"id_alumni" => 33,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2000",
				"tahun_masuk" => "1999",
				"angkatan" => 38,
				"id_alumni" => 33,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "1998",
				"tahun_masuk" => "1995",
				"angkatan" => 37,
				"id_alumni" => 34,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1987",
				"tahun_masuk" => "1984",
				"angkatan" => 26,
				"id_alumni" => 35,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2001",
				"tahun_masuk" => "1997",
				"angkatan" => 39,
				"id_alumni" => 40,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2001",
				"tahun_masuk" => "1997",
				"angkatan" => 39,
				"id_alumni" => 41,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2001",
				"tahun_masuk" => "1997",
				"angkatan" => 39,
				"id_alumni" => 42,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2001",
				"tahun_masuk" => "1997",
				"angkatan" => 39,
				"id_alumni" => 43,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1961",
				"tahun_masuk" => "1958",
				"angkatan" => 1,
				"id_alumni" => 44,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2016",
				"tahun_masuk" => "2012",
				"angkatan" => 55,
				"id_alumni" => 45,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2016",
				"tahun_masuk" => "2012",
				"angkatan" => 55,
				"id_alumni" => 46,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "1998",
				"tahun_masuk" => "1995",
				"angkatan" => 37,
				"id_alumni" => 47,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2000",
				"tahun_masuk" => "1998",
				"angkatan" => 39,
				"id_alumni" => 47,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1997",
				"tahun_masuk" => "1994",
				"angkatan" => 36,
				"id_alumni" => 48,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2000",
				"tahun_masuk" => "1997",
				"angkatan" => 38,
				"id_alumni" => 48,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2000",
				"tahun_masuk" => "1998",
				"angkatan" => 38,
				"id_alumni" => 49,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2011",
				"tahun_masuk" => "2007",
				"angkatan" => 49,
				"id_alumni" => 50,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2003",
				"tahun_masuk" => "1999",
				"angkatan" => 41,
				"id_alumni" => 51,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1985",
				"tahun_masuk" => "",
				"angkatan" => 24,
				"id_alumni" => 19,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1985",
				"tahun_masuk" => "",
				"angkatan" => 24,
				"id_alumni" => 20,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1996",
				"tahun_masuk" => "1993",
				"angkatan" => 35,
				"id_alumni" => 58,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2003",
				"tahun_masuk" => "1999",
				"angkatan" => 41,
				"id_alumni" => 58,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "1999",
				"tahun_masuk" => "1995",
				"angkatan" => 38,
				"id_alumni" => 21,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1996",
				"tahun_masuk" => "",
				"angkatan" => 35,
				"id_alumni" => 28,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2000",
				"tahun_masuk" => "",
				"angkatan" => 35,
				"id_alumni" => 28,
			],
			[
				"jenjang" => "D-III",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1990",
				"tahun_masuk" => "",
				"angkatan" => 29,
				"id_alumni" => 36,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2002",
				"tahun_masuk" => "",
				"angkatan" => 40,
				"id_alumni" => 36,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2001",
				"tahun_masuk" => "",
				"angkatan" => 39,
				"id_alumni" => 37,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2001",
				"tahun_masuk" => "",
				"angkatan" => 39,
				"id_alumni" => 38,
			],
			[
				"jenjang" => "D-IV",
				"instansi" => "Sekolah Tinggi Ilmu Statistik",
				"tahun_lulus" => "2002",
				"tahun_masuk" => "",
				"angkatan" => 40,
				"id_alumni" => 39,
			],
			[
				"jenjang" => "D4",
				"instansi" => "Akademi Ilmu Statistik",
				"tahun_lulus" => "1951",
				"tahun_masuk" => "1950",
				"angkatan" => 25,
				"id_alumni" => 1,
			],
		];
		$this->db->table('pendidikan')->insertBatch($data);

		$data = [
			[
				"id_pendidikan" => "1",
				"program_studi" => "D-III AIS",
				"nim" => "1320",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "2",
				"program_studi" => "Statistik Sosial Kependudukan",
				"nim" => "01.0258",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "3",
				"program_studi" => "D-III AIS",
				"nim" => "1264",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "4",
				"program_studi" => "D-III AIS",
				"nim" => "1281",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "5",
				"program_studi" => "D-III AIS",
				"nim" => "1274",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "6",
				"program_studi" => "Ak. Ilmu Statistik",
				"nim" => "559",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "7",
				"program_studi" => "D-IV Statistik Sosial Kependudukan",
				"nim" => "SK.07.5525",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "8",
				"program_studi" => "D-IV Statistik Ekonomi",
				"nim" => "SE.07.5510",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "9",
				"program_studi" => "D-III AIS",
				"nim" => "270",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "10",
				"program_studi" => "D-IV SK",
				"nim" => "SK.01.0186",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "11",
				"program_studi" => "D-IV SK",
				"nim" => "SK.01.0275 ",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "12",
				"program_studi" => "D-III STIS",
				"nim" => "95.2655",
				"judul_tulisan" => "Analisis Ubinan Kota Wonogiri 1997",
			],
			[
				"id_pendidikan" => "13",
				"program_studi" => "D-IV Statistik Sosial Kependudukan",
				"nim" => "SK.00.0118",
				"judul_tulisan" => "Mortalitas Penduduk Indonesia",
			],
			[
				"id_pendidikan" => "14",
				"program_studi" => "D-III STIS",
				"nim" => "95.2679",
				"judul_tulisan" => "Judul Tulisannya Apa ya",
			],
			[
				"id_pendidikan" => "15",
				"program_studi" => "D-IV Komputasi Statistik",
				"nim" => "KS.09.6024",
				"judul_tulisan" => "Clustering Indeks Pembangunan Manusia hihi",
			],
			[
				"id_pendidikan" => "16",
				"program_studi" => "D-IV Komputasi Statistik",
				"nim" => "KS.09.6027",
				"judul_tulisan" => "Remote Sensing ajah pokoknya",
			],
			[
				"id_pendidikan" => "17",
				"program_studi" => "D-III AIS",
				"nim" => "1188",
				"judul_tulisan" => "Disparitas Distribusi Pendapatan dan Variabel-Variabel yang Mempengaruhinya",
			],
			[
				"id_pendidikan" => "18",
				"program_studi" => "D-IV Statistik Sosial Kependudukan",
				"nim" => "SK.01.0171 ",
				"judul_tulisan" => "Faktor-faktor yang Mempengaruhi Perawatan Kehamilan",
			],
			[
				"id_pendidikan" => "19",
				"program_studi" => "D-III AIS",
				"nim" => "1209",
				"judul_tulisan" => "Ketimpangan Capaian Pendidikan di Indonesia dan Determinannya",
			],
			[
				"id_pendidikan" => "20",
				"program_studi" => "D-III AIS",
				"nim" => "1842",
				"judul_tulisan" => "Analisis Sistem Keamanan Jaringan Hot-Spot",
			],
			[
				"id_pendidikan" => "21",
				"program_studi" => "Komputasi Statistik",
				"nim" => "KS.14.8287",
				"judul_tulisan" => "Analisis Sistem Keamanan Jaringan Hot-Spot",
			],
			[
				"id_pendidikan" => "22",
				"program_studi" => "Statistik Ekonomi",
				"nim" => "SE.14.8316",
				"judul_tulisan" => "Analisis Efisiensi Penggunaan Modal Kerja Untuk Kegiatan Usaha Pada Perusahaan Konveksi Perusahaan",
			],
			[
				"id_pendidikan" => "23",
				"program_studi" => "Komputasi Statistik",
				"nim" => "KS.10.6395",
				"judul_tulisan" => "Analisa Struktur Kalimat Bahasa Indonesia dengan Menggunakan Pengurai Kalimat Berbasis Linguistik",
			],
			[
				"id_pendidikan" => "24",
				"program_studi" => "D-IV Statistik Sosial Kependudukan",
				"nim" => " SK.04.4611",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "25",
				"program_studi" => "D-IV Statistik Sosial Kependudukan",
				"nim" => " SK.03.4145",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "26",
				"program_studi" => "D-IV Statistik Ekonomi",
				"nim" => "SE.03.4182 ",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "27",
				"program_studi" => "D-IV Statistik Ekonomi",
				"nim" => "SE.02.0398",
				"judul_tulisan" => "Analisis Prediksi Hari Kiamat 2012 Dengan Metode Monte Carlo",
			],
			[
				"id_pendidikan" => "28",
				"program_studi" => "D-III STIS",
				"nim" => "96.2782",
				"judul_tulisan" => "Analisis Peubah Ganda",
			],
			[
				"id_pendidikan" => "29",
				"program_studi" => "D-IV Statistik Ekonomi",
				"nim" => "SE.99.0052",
				"judul_tulisan" => "Kecerdasan Buatan",
			],
			[
				"id_pendidikan" => "30",
				"program_studi" => "D-III STIS",
				"nim" => "95.2623",
				"judul_tulisan" => "Sadis, seorang istri tega menjemur dan memukuli kasur karna ketahuan sudah ditiduri suaminya",
			],
			[
				"id_pendidikan" => "31",
				"program_studi" => "Ak. Ilmu Statistik",
				"nim" => "1271",
				"judul_tulisan" => "Ingin mempunyai umur yang panjang seorang kakek berpura-pura budek ketika dipanggil malaikat",
			],
			[
				"id_pendidikan" => "32",
				"program_studi" => "D-IV Statistik Sosial Kependudukan",
				"nim" => "SK.00.0127",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "33",
				"program_studi" => "D-IV Statistik Sosial Kependudukan",
				"nim" => "SK.00.0082",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "34",
				"program_studi" => "D-IV Statistik Ekonomi",
				"nim" => "SE.00.0152",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "35",
				"program_studi" => "D-IV Komputasi Statistik",
				"nim" => "KS.00.0067",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "36",
				"program_studi" => "D-III AIS",
				"nim" => "1",
				"judul_tulisan" => "Analisis Klaster Menggunakan Metode Hierarchical Clustering",
			],
			[
				"id_pendidikan" => "37",
				"program_studi" => "D-IV Statistik Ekonomi",
				"nim" => "SE.12.7157",
				"judul_tulisan" => "Pengaruh Virus H5N1 terhadap Perekonomian di Provinsi Banten",
			],
			[
				"id_pendidikan" => "38",
				"program_studi" => "D-IV Komputasi Statistik",
				"nim" => "KS.12.7151",
				"judul_tulisan" => "Perancangan Sistem Pakar Pendeteksi Gangguan Kecemasan Berbasis Web",
			],
			[
				"id_pendidikan" => "39",
				"program_studi" => "D-III STIS",
				"nim" => "95.2691",
				"judul_tulisan" => "Analisis Pola Fertilitas Wanita Usia Subur di Indonesia tahun 1997",
			],
			[
				"id_pendidikan" => "40",
				"program_studi" => "D-IV Statistik Ekonomi",
				"nim" => "SE..98.0036",
				"judul_tulisan" => "Kesalahan Spesifikasi Model pada Data Cacah Menyebabkan Overdispersi",
			],
			[
				"id_pendidikan" => "41",
				"program_studi" => "Ak. Ilmu Statistik",
				"nim" => "2515",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "42",
				"program_studi" => "D-IV Statistik Sosial Kependudukan",
				"nim" => "SK.99.0055 ",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "43",
				"program_studi" => "D-IV Komputasi Statistik",
				"nim" => "KS.98.0019 ",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "44",
				"program_studi" => "D-IV Komputasi Statistik",
				"nim" => "KS.07.5297",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "45",
				"program_studi" => "D-IV Statistik Ekonomi",
				"nim" => "SE.02.0365",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "46",
				"program_studi" => "D-III AIS",
				"nim" => "1226",
				"judul_tulisan" => "Kemiskinan Multidimensi dan Variabel yang Mempengaruhinya",
			],
			[
				"id_pendidikan" => "47",
				"program_studi" => "D-III AIS",
				"nim" => "1200",
				"judul_tulisan" => "Pemilihan Model Terbaik pada Peramalan Produksi Batubara di Indonesia",
			],
			[
				"id_pendidikan" => "48",
				"program_studi" => "Ak. Ilmu Statistik",
				"nim" => "2421",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "49",
				"program_studi" => "D-IV Statistik Ekonomi",
				"nim" => "SE.02.0433",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "50",
				"program_studi" => "Komputasi Statistik",
				"nim" => "KS.97.0008",
				"judul_tulisan" => "Analisis Data Geospasial Media Sosial untuk Melihat Pola Pariwisata di Indonesia",
			],
			[
				"id_pendidikan" => "51",
				"program_studi" => "D-III AIS",
				"nim" => "2353",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "52",
				"program_studi" => "D-IV SE",
				"nim" => "SE.99.0054",
				"judul_tulisan" => "",
			],
			[
				"id_pendidikan" => "53",
				"program_studi" => "D-III AIS",
				"nim" => "2314",
				"judul_tulisan" => "Pengeruh Skripsi Terhadap Kesehatan Mental",
			],
			[
				"id_pendidikan" => "54",
				"program_studi" => "D-IV Statistik Sosial Kependudukan",
				"nim" => "SK.01.0199",
				"judul_tulisan" => "Pengaruh Pertumbuhan Penduduk terhadap Harga Pasar",
			],
			[
				"id_pendidikan" => "55",
				"program_studi" => "D-IV Statistik Sosial Kependudukan",
				"nim" => "SK.00.0103",
				"judul_tulisan" => "Pengaruh Nilai terhadap Presatasi",
			],
			[
				"id_pendidikan" => "56",
				"program_studi" => "D-IV Statistik Sosial Kependudukan",
				"nim" => "SK.00.0093",
				"judul_tulisan" => "Binggung bikin judul",
			],
			[
				"id_pendidikan" => "57",
				"program_studi" => "D-IV Statistik Ekonomi",
				"nim" => "SE.01.0210 ",
				"judul_tulisan" => "Pokoknya Judul",
			],
			[
				"id_pendidikan" => "58",
				"program_studi" => "Komputasi",
				"nim" => "221810",
				"judul_tulisan" => "Aww Malu banget",
			],
		];
		$this->db->table('pendidikan_tinggi')->insertBatch($data);
	}
}
